/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 */


import io.ark.core.Account
import io.ark.core.Network
import io.ark.core.Transaction
import spock.lang.Shared
import spock.lang.Specification
import spock.lang.Timeout

import java.util.concurrent.TimeUnit

class AccountTest extends Specification {

  @Shared mainnet = Network.Mainnet
  @Shared devnet = Network.Devnet

  def setupSpec() {
    mainnet.warmup(2)
    devnet.warmup(2)
  }

  def "Should fetch Account balance"() {
    setup:
    def account = new Account('D6wZQMhGUZ3xCk5CEQPXTxoniWLms9R1FC', devnet)

    when:
    account.updateBalance()

    then:
    account.getBalance() > 0
  }

}
